Box_Plot:
  color: coolwarm
  detail: true
  scale: log10
  test: U-test
  test_format: simple
General:
  color: coolwarm
  fig_format: png
  merge: false
  segmentation: data
  style: white
Line_Plot:
  color: deep
  vertical_line: None
  xlabel: None
Scatter_Plot:
  BCV: None
  color: deep
  scale: log2
  show_others: false
  x_axis: 1
